### ISSUE TITLE
Thanks submitting this lib to Gank.io.

### ISSUE THREAD

**Issue by daimajia** [youngkaaa/YViewPagerDemo#1]
Hey, thanks for submitting this lib to [gank.io ](http://gank.io).

It's a pretty good lib, I really want to publish it, but there are still some minor issues need to fix or enhance:

- English README 
- Add an License for this project 
- Maven support
- Prettify your demo screenshot
- Ignore .idea folder
- Remove external Chinese website link

Thanks for your work on this project, looking forward to your feedback.

**Comment by junyuecao** [comment]
U r awesome!

**Comment by youngkaaa** [comment]
yeah,I just finish the 
- English README
- Add an License for this project
- Ignore .idea folder
- Remove external Chinese website link

and the `Maven support` I had upload this lib,just wait for through. And `Prettify your demo screenshot` I had try my best to record it

**Comment by daimajia** [comment]
Well done.
