### ISSUE TITLE
最新demo跑步起来

### ISSUE THREAD

**Issue by weijuner** [youngkaaa/YViewPagerDemo#4]
@Override
    public void draw(Canvas canvas) {
        super.draw(canvas);
        boolean needsInvalidate = false;
空指针

**Comment by youngkaaa** [comment]
我在mi 4 上面是可以跑起来的   最新版的是继承自ViewPager,可以换用一下这个类[YViewPagerOrigin](https://github.com/youngkaaa/YViewPagerDemo/blob/master/app/src/main/java/cn/youngkaaa/yviewpagerdemo/YViewPagerOrigin.java)，这个类是最开始的版本，继承自ViewGroup
