### ISSUE TITLE
和VerticalTabLayout一起用   你这个下标越界啊

### ISSUE THREAD

**Issue by 4what2do** [youngkaaa/YViewPagerDemo#5]

**Comment by youngkaaa** [comment]
是跑的里面的的[VerticalActivity](https://github.com/youngkaaa/YViewPagerDemo/blob/master/app/src/main/java/cn/youngkaaa/yviewpagerdemo/VerticalActivity.java)出现的下标越界吗？

**Comment by 4what2do** [comment]
大哥 我错了  和 VerticalTabLayout 一起用的时候  没注意  复制粘贴的时候把你这布局文件里的app:circulatory="true"这行代码没删 是个乌龙

**Comment by youngkaaa** [comment]
这句话可以加上，但是下标需要你自己特殊处理，而且竖直滑动时循环滑动很少，基本都是左右联动就可以了
